language: java
jdk: oraclejdk8

sudo: false

script:
  #- ./gradlew --continue check javadoc jacocoTestReport
  - ./gradlew --continue check jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find ~/.gradle/ -name *.lock -print0 | xargs -0 rm -f
cache:
  directories:
  - ~/.gradle
